/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 5.7 */
/* Thu Nov 04 17:50:16 2021 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ), .LOCK( ));
